project:
  type: book
  output-dir: docs


book:
  title: "mapsR: A guide to data analysis with R"
  output-file: "mapsR"
  # date: today
  # cover-image: cover.png
  # last-changed: today
  repo-url: https://github.com/dzvoti/mapsR/
  repo-actions: [edit]
  # downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - timetable.qmd
    - intro.qmd
    - data_types.qmd
    - data_structures.qmd
    - reading_data.qmd
    - writing_data.qmd
    - data_wrangling.qmd
    - big_data.qmd
    - functions.qmd
    - data_visualisation.qmd
    - basic_statistics.qmd
    - jura.qmd
  sidebar:
    tools:
      - icon: cloud-arrow-down
        href: https://dzvoti.github.io/mapsR/data.zip
        aria-label: Download data

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
    toc-title: "On this page"
  pdf:
    documentclass: scrreprt

editor: source

# Do not evaluate code chunks
eval: false
callout-icon: false

